# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-dockerfile
build_from:
  aarch64: "ghcr.io/sysadminsmedia/homebox:0.17-arm"
  amd64: "ghcr.io/sysadminsmedia/homebox:0.17"
  armv7: "ghcr.io/sysadminsmedia/homebox:0.17-arm"
labels:
  org.opencontainers.image.title: "Home Assistant Add-on: Homebox"
  org.opencontainers.image.description: "Run Homebox inside Home Assistant"
  org.opencontainers.image.source: "https://github.com/jscarrott/homebox-addon"
  org.opencontainers.image.licenses: "Apache-2.0"
args:
  TEMPIO_VERSION: "2021.09.0"
