#!/bin/sh
# Start the Homebox service

# Ensure tmp dir exists (fallback in case init script didn't run)
mkdir -p /data/tmp

export TMPDIR="/data/tmp"

echo "Starting Homebox"

if [ -f /data/config.yml ]; then
  exec /app/api /data/config.yml
fi

exec /app/api
